### ISSUE TITLE
Точки от проекти

### ISSUE THREAD

**Issue by mstoykov** [skanev/evans#169]
Към текущия момент няма как да се запишат точките от проектите в сайта на курса. 

Предлагам да се въвеждат подобно на "признанията", но с поленце за точките вместо за линк. И да има отделна колонка на страницата с точките.

В допълнение: 
Курса по Go (предполагам и други) има и първа защита на проекта. Тази защита е преди сесията и носи до 10 точки. Няма да е лошо и те да могат да бъдат въвеждани в сайта, макар че и общото поле ще свърши работи, две различни биха били по добре :smile:

**Comment by s2gatev** [comment]
Това май се track-ва вече - #85

Първата защита на проект може да се моделира като домашна с 10 точки + отнемане на такива, ако е необходимо?

**Comment by mitio** [comment]
Като се замисля, и проектите могат да минат така. Ще го помисля.

**Comment by s2gatev** [comment]
Не знам до колко е удачно, защото те изискват повече функционалност.

Един проект се състои от:
1. Описание - Необходима е функционалност, която да позволява на студент и преподавател да дискутират предложението за проект и да се спрат на финална идея, която да е маркирана и добре описана някъде. В момента Go курса ползва форума за това, но според мен е добре такава информация да си има специално място. Преди време бях говорил със @skanev за подобна механика.
2. Точки - В повечето курсове, ползващи тази система точките на проект се дават в различни категории - функционалност, добър код, тестове,... Да ползваме "задача" за това е по-скоро бързото решение. Тази информация също може да се систематизира.

Ако причината да не се направи нещо повече е, че няма кой да го направи, аз бих работил върху това веднага щом се разберем какво точно ни трябва.

**Comment by mitio** [comment]
Да, използване на задачите за целта по-скоро би било workaround, а не добро решение.

Иначе, заданието на проекта може да се събмитва като код на задачата и задачата да се маркира като "ръчно проверяване". В коментарите към задачата може да се дискутира заданието. Крайният срок на задачата "проект" може да е крайната дата за предаване на проект.

Но, да, това си е workaround.

В момента наистина няма кой да го направи и затова не се прави. Ако имаш вдъхновение, може да предложиш нещо в PR.

**Comment by ironsmile** [comment]
Подкрепям идеята проектите да са "вградена" част от evans. Те са, може би, най - важната част от курсовете и невъзможността да бъдат нормално отразени на сайта създава излишни главоболия.

Имаме опит от използване на задачи за описание на проект. Този workaround е изключително неудобен. Основните му проблеми са това, че се очаква студентите да направят предложението си във "валиден код" и това, че не е възможно нормално форматиране. Първото води до оплаквания "не можах да си предам предложението". Второто до [много трудно четими предложения](http://fmi.py-bg.net/tasks/4/solutions/484). Плюсът му е, че след това има къде да се сложат точките от проекта.

Имаме и опит с обсъждането и одобряване на проекти чрез тема във форума. Минуса на този подход е, че няма къде да запишат точките след това. Което е основната причина за отваряне на това issue. Плюса е, че форума се използва точно по начина, по който се очаква - за дискусия. Това насърчава студентите да разглеждат проектите един на друг.

Предложението на @s2gatev е възможно най - правилния начин да се реши проблема. Наистина, в момента съществува объркване дали проект е одобрен от преподаващ или не. Идеите на студентите се разпростират из няколко коментара и/или обсъждания на живо. Маркиране и одобряване на идеята за проект на ясно централно място ще реши този проблем.

Но същевременно виждам няколко проблема с предложението. Със сигурност за избор на проект ще трябва да има възможност за дискусия. Това ще изисква или повторение на функционалността от форума или всъщност използване на форума за това. Истина е, че проектите се оценяват в различни категории. Но за всеки курс тези категории са различни и би било трудно да се измисли система, която да обхване всички от тях.

Поради това си мисля, че предложението в #85 (отново на @s2gatev) е по - добрия подход. Просто поле в което да се добавят точките за проекта на определен студент. Ще е, наистина, стимулиращо ако те се виждат на профилната му страница и в таблицата с точки (`/points_breakdowns`).

**Comment by skanev** [comment]
Това е готина идея, аз я одобрявам. Ако имах време, щях да съм я имплементирал вече.

Ако някой от вас иска да го имплементира, нека да си каже. Ще отделя час два да седнем и да му измислим дизайна и ще ви покажа мотиките, които можете да настъпите.
