### ISSUE TITLE
Tip of the day

### ISSUE THREAD

**Issue by skanev** [skanev/evans#35]
"Tip of the day" е работно име. Може би "съвети"?.

Първо, преподавателите трябва да могат да публикуват кратки съвети (Markdown форматирани) от време на време. Тези съвети трябва да са лесно достъпни за студентите. Всеки съвет е bite-sized (1-2 абзаца) и е нещо конкретно.

Второ, студентите трябва да могат да предлагат такива съвети. Добрите биват възнаградени с бонус точки.

**Comment by s2gatev** [comment]
Това "хитринките" ли са? Или се има нещо друго предвид?

**Comment by mitio** [comment]
Да, хитринките са.
